### ISSUE TITLE
Plz license

### ISSUE THREAD

**Issue by NCLI** [nqpz/bankogen#1]
Hej, gider du smide en licens på dit slam?

Ville gerne forke, men er jo teknisk set ikke lovligt uden en permissive licens.

**Comment by nqpz** [comment]
Kære NCLI

Hermed gjort.

Venlig hilsen Niels

P.S. Vær opmærksom på at de genererede bankoplader ikke er helt rigtige (fx er de nulindekserede) og at de ikke er veldistribuerede (dvs. nogle bankoplader er der større sandsynlighed for at generere end andre).
